package com.hosuke.mapper;

import com.hosuke.entity.Post;
import com.hosuke.generated.pojo.PostExample;
import org.apache.ibatis.annotations.Param;

import java.util.Collection;
import java.util.List;

public interface PostMapper {

    Post selectById(Long id);

    List<Post> selectNotHidden();

    //TODO: Complete this part
//    @Query("SELECT p FROM Post p WHERE :tagCount = (SELECT COUNT(DISTINCT t.id) FROM Post p2 JOIN p2.tags t WHERE LOWER(t.name) in (:tags) and p = p2)")
//    List<Post> findByTags(@Param("tags") Collection<String> tags, @Param("tagCount") Long tagCount);
//
//    @Query("SELECT p FROM Post p WHERE :tagCount = (SELECT COUNT(DISTINCT t.id) FROM Post p2 JOIN p2.tags t WHERE p.hidden = false and LOWER(t.name) in (:tags) and p = p2)")
//    List<Post> findByTagsAndNotHidden(@Param("tags") Collection<String> tags, @Param("tagCount") Long tagCount);
//
//    @Query("SELECT p FROM Post p JOIN p.postRatings r WHERE p.hidden = false GROUP BY p ORDER BY SUM(r.value) DESC")
//    List<Post> findTopPosts();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Wed Mar 07 09:16:28 CST 2018
     */
    int countByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Wed Mar 07 09:16:28 CST 2018
     */
    int deleteByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Wed Mar 07 09:16:28 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Wed Mar 07 09:16:28 CST 2018
     */
    int insert(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Wed Mar 07 09:16:28 CST 2018
     */
    int insertSelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Wed Mar 07 09:16:28 CST 2018
     */
    List<Post> selectByExampleWithBLOBs(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Wed Mar 07 09:16:28 CST 2018
     */
    List<Post> selectByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Wed Mar 07 09:16:28 CST 2018
     */
    Post selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Wed Mar 07 09:16:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") Post record, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Wed Mar 07 09:16:28 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Post record, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Wed Mar 07 09:16:28 CST 2018
     */
    int updateByExample(@Param("record") Post record, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Wed Mar 07 09:16:28 CST 2018
     */
    int updateByPrimaryKeySelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Wed Mar 07 09:16:28 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table posts
     *
     * @mbggenerated Wed Mar 07 09:16:28 CST 2018
     */
    int updateByPrimaryKey(Post record);
}
